SELECT YEAR(t2.SALES_DATE) AS "YEAR", MONTH(t2.SALES_DATE) AS "MONTH", t1.GENDER, COUNT(DISTINCT t1.USER_ID) AS "USERS"
FROM USER_INFO t1
JOIN ONLINE_SALE t2
ON t1.USER_ID = t2.USER_ID
WHERE t1.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, t1.GENDER
ORDER BY YEAR, MONTH, t1.GENDER