SELECT t1.CATEGORY, PRICE AS 'MAX_PRICE', t1.PRODUCT_NAME
FROM FOOD_PRODUCT AS t1,
(SELECT MAX(PRICE) AS max_price FROM FOOD_PRODUCT GROUP BY CATEGORY) AS t2
WHERE (CATEGORY = '과자' OR CATEGORY = '국' OR CATEGORY = '김치' OR CATEGORY = '식용유') AND t1.PRICE = t2.max_price
GROUP BY CATEGORY
ORDER BY PRICE desc