SELECT t1.FOOD_TYPE, t1.REST_ID, t1.REST_NAME, t1.FAVORITES
FROM REST_INFO AS t1,
(SELECT FOOD_TYPE, MAX(FAVORITES) AS max_favorites FROM REST_INFO GROUP BY FOOD_TYPE) AS t2
WHERE t1.FAVORITES = t2.max_favorites AND t1.FOOD_TYPE = t2.FOOD_TYPE
ORDER BY t1.FOOD_TYPE desc;