SELECT app.APNT_NO, pat.PT_NAME, pat.PT_NO, app.MCDP_CD, doc.DR_NAME, app.APNT_YMD
FROM APPOINTMENT app
JOIN PATIENT pat
ON app.PT_NO = pat.PT_NO
JOIN DOCTOR doc
ON app.MDDR_ID = doc.DR_ID
WHERE DATE_FORMAT(app.APNT_YMD, "%Y-%m-%d") = "2022-04-13" AND app.APNT_CNCL_YN = "N" AND app.MCDP_CD = "CS"
GROUP BY pat.PT_NO
ORDER BY app.APNT_YMD